name: Second

on:
  workflow_run:
    workflows: [First]
    types: [completed]
    branches: [main]

jobs:
  first:
    name: Run step in Second workflow
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Triggering event:"
          echo "$GITHUB_CONTEXT" | jq
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - run: sleep 30
